name: pos_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  lottie: ^3.3.1
  go_router: ^14.0.2
  flutter_vector_icons: ^2.0.0 # Add this line for vector icons (including Feather icons)
  mobile_scanner: ^3.5.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  provider: ^6.1.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_splash.jpg
